import React, { useState, useMemo, useEffect } from 'react';
import { Search, Filter, Download, Plus, Mail, Edit, Trash2, Globe, Calendar, CreditCard, ChevronDown, ChevronRight, FileText, Eye, ChevronLeft } from 'lucide-react';
import { DomainClient, Invoice } from '../types';
import { useAuth } from '../context/AuthContext';
import { useData } from '../context/DataContext';
import { useNotification } from '../context/NotificationContext';
import { DB } from '../services/db';
import { InvoiceService } from '../services/invoiceService';
import AiEmailModal from '../components/AiEmailModal';
import EditDomainModal from '../components/EditDomainModal';
import InvoiceViewModal from '../components/InvoiceViewModal';
import ConfirmationModal from '../components/ConfirmationModal';
import { useDebounce } from '../hooks/useDebounce';

const Domains: React.FC = () => {
  const { domains, invoices, updateDomain, deleteDomain } = useData();
  const [searchTerm, setSearchTerm] = useState('');
  const debouncedSearchTerm = useDebounce(searchTerm, 300);
  const [statusFilter, setStatusFilter] = useState<string>('All');
  const [selectedClientForEmail, setSelectedClientForEmail] = useState<DomainClient | null>(null);
  const [editingDomain, setEditingDomain] = useState<DomainClient | null>(null);
  const [expandedClientId, setExpandedClientId] = useState<string | null>(null);
  const [viewInvoice, setViewInvoice] = useState<Invoice | null>(null);
  const [deleteConfirmation, setDeleteConfirmation] = useState<{isOpen: boolean, domain: DomainClient | null}>({ isOpen: false, domain: null });
  
  // Pagination State
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(10);
  
  const { user, formatCurrency, dataFields, settings } = useAuth();
  const { addNotification } = useNotification();

  const isAdminOrManager = ['Super Admin', 'Admin', 'Manager'].includes(user?.role || '');

  const filteredDomains = useMemo(() => {
    return domains.filter(domain => {
      const term = debouncedSearchTerm.toLowerCase().trim();
      
      const matchesSearch = 
        term === '' ||
        domain.clientName.toLowerCase().includes(term) || 
        domain.domainName.toLowerCase().includes(term) ||
        domain.email.toLowerCase().includes(term) ||
        (domain.invoiceNumber && domain.invoiceNumber.toLowerCase().includes(term));

      const matchesStatus = statusFilter === 'All' || domain.status === statusFilter;
      
      return matchesSearch && matchesStatus;
    });
  }, [domains, debouncedSearchTerm, statusFilter]);

  // Reset pagination when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [debouncedSearchTerm, statusFilter]);

  // Pagination Logic
  const totalPages = Math.ceil(filteredDomains.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const paginatedDomains = filteredDomains.slice(startIndex, startIndex + itemsPerPage);

  const handlePageChange = (newPage: number) => {
    if (newPage >= 1 && newPage <= totalPages) {
        setCurrentPage(newPage);
    }
  };

  const getStatusColor = (status: string) => {
    const s = status.toLowerCase();
    if (s === 'active') return 'bg-green-100 text-green-700';
    if (s === 'pending') return 'bg-yellow-100 text-yellow-700';
    if (s === 'expired') return 'bg-red-100 text-red-700';
    return 'bg-slate-100 text-slate-700';
  };

  const getPaymentStatusColor = (status: string) => {
    const s = status.toLowerCase();
    if (s === 'paid') return 'text-green-600';
    if (s === 'overdue') return 'text-red-600 font-semibold';
    if (s === 'unpaid') return 'text-orange-600';
    return 'text-slate-600';
  };

  const handleUpdateDomain = (updatedDomain: DomainClient) => {
    // DataContext handles the syncing logic now
    updateDomain(updatedDomain);
    
    // Note: Immediate invoice generation has been disabled.
    // Invoices will be generated by the automation service 7-10 days before renewal.

    const existing = domains.find(d => d.id === updatedDomain.id);
    setEditingDomain(null);

    if (!existing) {
       addNotification('New Client Added', `${updatedDomain.clientName} and domain ${updatedDomain.domainName} registered.`, 'hosting');
    } else {
       addNotification('Domain Updated', `Records for ${updatedDomain.domainName} have been updated.`, 'hosting');
    }
  };

  const confirmDeleteDomain = (domain: DomainClient) => {
    setDeleteConfirmation({ isOpen: true, domain });
  };

  const handleExecuteDelete = () => {
    if (deleteConfirmation.domain) {
      deleteDomain(deleteConfirmation.domain.id);
      addNotification('Domain Removed', `${deleteConfirmation.domain.domainName} was removed from the system.`, 'system');
      setDeleteConfirmation({ isOpen: false, domain: null });
    }
  };

  const handleAddDomain = () => {
    const settings = DB.getSettings();
    const period = settings.defaultDomainRenewalPeriod || '1 Year';
    const today = DB.getTodayLocal();
    const nextDate = DB.calculateDate(today, period);

    const newDomain: DomainClient = {
      id: `d${Date.now()}`,
      sl: domains.length > 0 ? Math.max(...domains.map(d => d.sl)) + 1 : 1,
      clientName: 'New Client',
      email: '',
      phone: '',
      domainName: 'example.com',
      purchaseDate: today,
      expiryDate: nextDate,
      validationDate: nextDate,
      amount: 15, // Default domain price
      paymentMethod: 'Credit Card',
      paymentStatus: 'Unpaid',
      status: 'Pending',
      invoiceNumber: '', // Start empty
      invoiceDate: '',
      notes: ''
    };
    setEditingDomain(newDomain);
  };

  const handleExportCSV = () => {
    const headers = ['Sl.', 'Client Name', 'Domain', 'Email', 'Purchase Date', 'Renewal Date', 'Validation Date', 'Amount', 'Payment Method', 'Payment Status', 'Status', 'Notes'];
    
    const csvContent = [
      headers.join(','),
      ...filteredDomains.map(d => [
        d.sl,
        `"${d.clientName}"`,
        d.domainName,
        d.email,
        d.purchaseDate,
        d.expiryDate,
        d.validationDate,
        d.amount,
        d.paymentMethod,
        d.paymentStatus,
        d.status,
        `"${d.notes || ''}"`
      ].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `domains_export_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    addNotification('Export Complete', 'Domain list exported to CSV successfully.', 'system');
  };

  const toggleRow = (clientId: string) => {
    if (expandedClientId === clientId) {
      setExpandedClientId(null);
    } else {
      setExpandedClientId(clientId);
    }
  };

  const getClientInvoices = (clientId: string) => {
    return invoices
      .filter(inv => inv.clientId === clientId)
      .sort((a, b) => new Date(b.issueDate).getTime() - new Date(a.issueDate).getTime());
  };

  const handleDownloadInvoice = (e: React.MouseEvent, invoice: Invoice) => {
    e.stopPropagation();
    InvoiceService.downloadPDF(invoice, settings);
  };

  return (
    <div className="p-4 lg:p-6 h-full flex flex-col">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-end mb-6 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Domain Clients</h1>
          <p className="text-slate-500">Manage domain clients, registrations, and renewals.</p>
        </div>
        {isAdminOrManager && (
          <button 
            onClick={handleAddDomain}
            className="bg-primary hover:bg-opacity-90 text-white px-4 py-2 rounded-lg flex items-center gap-2 transition-colors w-full sm:w-auto justify-center"
          >
            <Plus size={18} />
            Add New Client
          </button>
        )}
      </div>

      {/* Toolbar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm mb-6 flex flex-col sm:flex-row flex-wrap gap-4 items-stretch sm:items-center justify-between">
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 flex-1">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
            <input 
              type="text" 
              placeholder="Search Domain, Client, Email..." 
              className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-primary outline-none transition-all"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
          <div className="relative">
            <Filter className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
            <select 
              className="w-full sm:w-auto pl-10 pr-8 py-2 border border-slate-300 rounded-lg appearance-none bg-white focus:ring-2 focus:ring-primary outline-none cursor-pointer"
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
            >
              <option value="All">All Status</option>
              {dataFields.statuses.map(s => (
                <option key={s} value={s}>{s}</option>
              ))}
            </select>
          </div>
        </div>
        <button 
          onClick={handleExportCSV}
          className="flex items-center justify-center gap-2 px-4 py-2 border border-slate-300 rounded-lg hover:bg-slate-50 text-slate-600 transition-colors"
        >
          <Download size={18} />
          Export CSV
        </button>
      </div>

      {/* Data Table */}
      <div className="bg-white border border-slate-200 rounded-xl shadow-sm flex-1 overflow-hidden flex flex-col">
        <div className="overflow-auto custom-scrollbar flex-1">
          <table className="w-full text-left border-collapse whitespace-nowrap">
            <thead className="bg-slate-50 sticky top-0 z-10">
              <tr>
                <th className="p-3 w-8 border-b border-slate-200"></th> {/* Expand Toggle */}
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200 w-16">Sl.</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200 min-w-[200px]">Client Info</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">Domain</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">Status</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">Purchase Date</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">Renewal Date</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">Cost</th>
                <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200">Payment</th>
                {isAdminOrManager && <th className="p-3 text-xs font-semibold text-slate-500 uppercase tracking-wider border-b border-slate-200 text-right sticky right-0 bg-slate-50 shadow-[-4px_0_8px_-4px_rgba(0,0,0,0.1)]">Actions</th>}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {paginatedDomains.length === 0 ? (
                <tr>
                   <td colSpan={10} className="p-8 text-center text-slate-500">
                      {searchTerm ? 'No domains match your search.' : 'No domain records found.'}
                   </td>
                </tr>
              ) : paginatedDomains.map((domain) => (
                <React.Fragment key={domain.id}>
                  <tr 
                    onClick={() => toggleRow(domain.id)}
                    className={`hover:bg-slate-50/80 transition-colors group cursor-pointer ${expandedClientId === domain.id ? 'bg-slate-50/80' : ''}`}
                  >
                    <td className="p-3 text-slate-400">
                      {expandedClientId === domain.id ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                    </td>
                    <td className="p-3 text-sm text-slate-500">{domain.sl}</td>
                    <td className="p-3">
                      <div className="font-medium text-slate-900">{domain.clientName}</div>
                      <div className="text-sm text-slate-500">{domain.email}</div>
                    </td>
                    <td className="p-3">
                       <div className="flex items-center gap-2 text-slate-800 font-medium">
                          <Globe size={16} className="text-slate-400" />
                          {domain.domainName}
                       </div>
                    </td>
                    <td className="p-3">
                      <span className={`px-2 py-1 rounded-full text-xs font-medium ${getStatusColor(domain.status)}`}>
                        {domain.status}
                      </span>
                    </td>
                    <td className="p-3 text-sm text-slate-600">
                      {domain.purchaseDate}
                    </td>
                    <td className="p-3 text-sm text-slate-700">
                      <div className="flex items-center gap-2">
                          <Calendar size={14} className="text-slate-400"/>
                          {domain.expiryDate}
                          {new Date(domain.expiryDate) < new Date(new Date().setMonth(new Date().getMonth() + 1)) && (
                            <span className="ml-2 text-rose-500 text-xs font-bold bg-rose-50 px-1.5 py-0.5 rounded border border-rose-100 uppercase">Soon</span>
                          )}
                      </div>
                    </td>
                    <td className="p-3 text-sm font-medium text-slate-900">
                      {formatCurrency(domain.amount)}
                    </td>
                    <td className="p-3 text-sm">
                      <div className="flex flex-col">
                          <span className={`font-medium ${getPaymentStatusColor(domain.paymentStatus)}`}>
                          {domain.paymentStatus}
                          </span>
                          <span className="text-xs text-slate-400 flex items-center gap-1">
                               <CreditCard size={10} /> {domain.paymentMethod}
                          </span>
                      </div>
                    </td>
                    {isAdminOrManager && (
                      <td className="p-3 text-right sticky right-0 bg-white group-hover:bg-slate-50 shadow-[-4px_0_8px_-4px_rgba(0,0,0,0.05)]" onClick={(e) => e.stopPropagation()}>
                        <div className="flex items-center justify-end gap-2">
                          <button 
                             onClick={() => setSelectedClientForEmail(domain)}
                             className="p-1.5 text-primary hover:bg-indigo-50 rounded-lg tooltip"
                             title="Send Renewal Notification"
                           >
                             <Mail size={16} />
                           </button>
                          <button 
                            onClick={() => setEditingDomain(domain)}
                            className="p-1.5 text-slate-500 hover:bg-slate-100 rounded-lg tooltip"
                            title="Edit Domain"
                          >
                            <Edit size={16} />
                          </button>
                          <button 
                            onClick={() => confirmDeleteDomain(domain)}
                            className="p-1.5 text-red-500 hover:bg-red-50 rounded-lg"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </td>
                    )}
                  </tr>

                  {/* Expanded Detail View */}
                  {expandedClientId === domain.id && (
                    <tr className="bg-slate-50 border-b border-slate-100">
                      <td colSpan={10} className="p-0">
                        <div className="py-4 pl-8 border-l-2 border-indigo-200 my-2 grid grid-cols-1 lg:grid-cols-2 gap-6 mx-4 animate-fade-in">
                           
                           {/* Invoices Section */}
                           <div>
                               <div className="flex items-center gap-2 mb-3 text-sm font-semibold text-slate-700">
                                  <FileText size={16} className="text-indigo-500" />
                                  <span>Recent Invoice History</span>
                               </div>
                               
                               <div className="bg-white border border-slate-200 rounded-lg overflow-hidden shadow-sm max-w-4xl h-[200px] overflow-y-auto custom-scrollbar">
                                  <table className="w-full text-left text-sm">
                                     <thead className="bg-slate-100 text-slate-600 font-semibold border-b border-slate-200 sticky top-0">
                                        <tr>
                                           <th className="p-3">Invoice #</th>
                                           <th className="p-3">Date</th>
                                           <th className="p-3">Amount</th>
                                           <th className="p-3">Status</th>
                                           <th className="p-3 text-right">Action</th>
                                        </tr>
                                     </thead>
                                     <tbody className="divide-y divide-slate-100">
                                        {getClientInvoices(domain.id).length === 0 ? (
                                           <tr>
                                              <td colSpan={5} className="p-4 text-center text-slate-400 italic">
                                                 No invoice history found.
                                              </td>
                                           </tr>
                                        ) : (
                                           getClientInvoices(domain.id).map(inv => (
                                              <tr key={inv.id} className="hover:bg-slate-50">
                                                 <td className="p-3 font-mono text-slate-700">{inv.invoiceNumber}</td>
                                                 <td className="p-3 text-slate-600">{inv.issueDate}</td>
                                                 <td className="p-3 font-medium">{formatCurrency(inv.amount)}</td>
                                                 <td className="p-3">
                                                    <span className={`px-2 py-0.5 rounded text-xs font-bold ${
                                                       inv.status === 'Paid' ? 'bg-green-100 text-green-700' :
                                                       inv.status === 'Overdue' ? 'bg-red-100 text-red-700' :
                                                       'bg-yellow-100 text-yellow-700'
                                                    }`}>
                                                       {inv.status}
                                                    </span>
                                                 </td>
                                                 <td className="p-3 text-right">
                                                    <div className="flex justify-end gap-2">
                                                       <button 
                                                          onClick={(e) => {
                                                            e.stopPropagation();
                                                            setViewInvoice(inv);
                                                          }}
                                                          className="text-slate-400 hover:text-slate-600 p-1" 
                                                          title="Preview"
                                                       >
                                                          <Eye size={16} />
                                                       </button>
                                                       <button 
                                                          onClick={(e) => handleDownloadInvoice(e, inv)}
                                                          className="text-primary hover:text-indigo-700 p-1" 
                                                          title="Download PDF"
                                                       >
                                                          <Download size={16} />
                                                       </button>
                                                    </div>
                                                 </td>
                                              </tr>
                                           ))
                                        )}
                                     </tbody>
                                  </table>
                               </div>
                           </div>

                           {/* Notes Section */}
                           <div className="flex flex-col h-full">
                                <div className="flex items-center gap-2 mb-3 text-sm font-semibold text-slate-700">
                                    <FileText size={16} className="text-indigo-500" />
                                    <span>Domain Notes</span>
                                </div>
                                <div className="bg-white border border-slate-200 rounded-lg shadow-sm p-4 text-sm text-slate-600 flex-1 h-[200px] overflow-y-auto custom-scrollbar">
                                    {domain.notes ? (
                                        <p className="whitespace-pre-wrap leading-relaxed">{domain.notes}</p>
                                    ) : (
                                        <p className="text-slate-400 italic">No notes added for this domain.</p>
                                    )}
                                </div>
                           </div>

                        </div>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
        
        {/* Pagination Footer */}
        {filteredDomains.length > 0 && (
            <div className="flex flex-col sm:flex-row justify-between items-center p-4 border-t border-slate-200 bg-slate-50 gap-4">
                <div className="text-xs text-slate-500">
                    Showing <span className="font-medium text-slate-700">{startIndex + 1}</span> to <span className="font-medium text-slate-700">{Math.min(startIndex + itemsPerPage, filteredDomains.length)}</span> of <span className="font-medium text-slate-700">{filteredDomains.length}</span> entries
                </div>
                <div className="flex items-center gap-2">
                    <select 
                        className="border border-slate-300 rounded-lg text-xs p-1.5 focus:ring-primary focus:border-primary outline-none bg-white text-slate-700 font-medium"
                        value={itemsPerPage}
                        onChange={(e) => {
                            setItemsPerPage(Number(e.target.value));
                            setCurrentPage(1); // Reset to page 1 on change
                        }}
                    >
                        <option value={10}>10 per page</option>
                        <option value={20}>20 per page</option>
                        <option value={50}>50 per page</option>
                        <option value={100}>100 per page</option>
                    </select>
                    <div className="flex items-center gap-1">
                        <button 
                            onClick={() => handlePageChange(currentPage - 1)}
                            disabled={currentPage === 1}
                            className="p-1.5 rounded-lg border border-slate-300 hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors text-slate-600"
                        >
                            <ChevronLeft size={16} />
                        </button>
                        <div className="px-2 text-xs font-medium text-slate-600">
                            Page {currentPage} of {totalPages || 1}
                        </div>
                        <button 
                            onClick={() => handlePageChange(currentPage + 1)}
                            disabled={currentPage === totalPages || totalPages === 0}
                            className="p-1.5 rounded-lg border border-slate-300 hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors text-slate-600"
                        >
                            <ChevronRight size={16} />
                        </button>
                    </div>
                </div>
            </div>
        )}
      </div>
      
      {selectedClientForEmail && (
        <AiEmailModal 
          client={selectedClientForEmail} 
          type="domain"
          isOpen={!!selectedClientForEmail}
          onClose={() => setSelectedClientForEmail(null)}
        />
      )}

      {editingDomain && (
        <EditDomainModal
          client={editingDomain}
          isOpen={!!editingDomain}
          onClose={() => setEditingDomain(null)}
          onSave={handleUpdateDomain}
        />
      )}

      {viewInvoice && (
        <InvoiceViewModal 
          invoice={viewInvoice} 
          isOpen={!!viewInvoice} 
          onClose={() => setViewInvoice(null)} 
        />
      )}
      <ConfirmationModal
        isOpen={deleteConfirmation.isOpen}
        title="Delete Domain"
        message={`Are you sure you want to remove ${deleteConfirmation.domain?.domainName}? This action cannot be undone.`}
        confirmLabel="Remove Domain"
        isDangerous={true}
        onConfirm={handleExecuteDelete}
        onCancel={() => setDeleteConfirmation({ isOpen: false, domain: null })}
      />
    </div>
  );
};

export default Domains;